### PR TITLE
Update to support Cassandra 3.x

### PR DESCRIPTION
**Pull request by seanryan41**
Contrast-Security-OSS/cassandra-migration#12

### CODE REVIEW

**Comment by seanryan41** [comment]
I've taken a stab at updating the dependency on cassandra-driver-core to v. 3.0.0.
1. System.schema_columnfamilies no longer exists in Cassandra 3, so I attempted to rewrite the tablesExist method to work the same way with out that table.
2. com.datastax.driver.core.GettableByNameData#getDate returns a com.datastax.driver.core.LocalDate instead of a Java Date, so I've updated the findAppliedMigrations method to use getTimestamp instead of getDate.

I've tested this with Cassandra 2.2.4 and 3.2.

**Comment by regis-leray** [comment]
+1 for this merge

**Comment by regis-leray** [comment]
@seanryan41 please rebase :)

**Comment by lis0x90** [comment]
+1 for this merge

**Comment by tonicebrian** [comment]
+1

**Comment by henningp** [comment]
+1

**Comment by MALPI** [comment]
+1

**Comment by swalendzik** [comment]
+1

**Comment by kubum** [comment]
+1

**Comment by seanryan41** [comment]
Hey guys, any chance this can get merged in? Thanks.

**Comment by nafeezmd** [comment]
+1

**Comment by gmcoringa** [comment]
+1

**Comment by hhandoko** [comment]
+1

**Comment by mgramin** [comment]
+1

**Comment by felixgao** [comment]
what is the status of this pull request?  I would like to use it, is there an ETA on the merge?

**Pull request merged**
